### PR TITLE
Upgrade mina-core to 2.0.21

### PR DESCRIPTION
**Pull request by reda-alaoui**

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Ping :)

**Comment by reda-alaoui** [comment]
Ping :)

**Comment by elecharny** [comment]
Hi Réda,

I sent you a private mail, not sure it maid it to your inbox...

**Comment by reda-alaoui** [comment]
Hi Emmanuel,
It didn’t. Let me confirm the email address via Twitter private messaging.

**Comment by reda-alaoui** [comment]
I can’t send you a private message on tweeter.
Feel free to contact me via Twitter PM.

**Pull request merged**
